kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: karthik
  name: expense-project
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  template:
    metadata:
      name: mysql
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
        - name: mysql
          image: joindevops/mysql:v1.0
