#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: frontend-config
# namespace: karthik
#data:
#  nginx.conf: #some logic is there need to see
---
kind: Deployment
apiVersion: v1
metadata:
  namespace: karthik
  name: frontend
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
        - name: frontend
          image: joindevops/frontend:1.2.0
          ports:
            - containerPort: 8080
          #envFrom:
          # - configMapRef:
          #  name: frontend
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: karthik
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expense
    tier: web
  port:
    - protocol: TCP
      targetPort: 80
      port: 80
