kind: ConfigMap
apiVersion: v1
metadata:
  namespace: karthik
  name: backend
data:
  DB_HOST: mysql #mysql component service name
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: karthik
  name: expense-backend
  labels:
    component: backend
    project: expense
    tier: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: apps
  template:
    metadata:
      name: expense-backend
      labels:
        component: backend
        project: expense
        tier: apps
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          envFrom:
            - configMapRef:
                name: backend
---
kind: Service
apiVersion: v1
metadata:
  namespace: karthik
  name: backend-service
spec:
  selector:
    component: backend
    project: expense
    tier: apps
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
